version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - yum groupinstall "Development Tools" -y
      - yum install cmake -y
      - mkdir build
      - cmake -B./build -H./ -DCELERO_ENABLE_TESTS
      - make -C ./build
      - tar -c ./build > celero.tar
      - ls -alt ./build
      - ls -alt ./build/bin
      - ./build/bin/Test*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - celero.tar
