version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ls -alt
      - which gcc
      - which g++
      - which clang
      - which cmake
      - cmake -v
      - git clone https://github.com/DigitalInBlue/Celero.git
      - mkdir celero/build
      - cmake -B./celero/build -H./celero -DCELERO_ENABLE_TESTS
      - make -j3 -C celero/build
      - tar -c ./celero/build > celero.tar
      - ./celero/build/bin/Test*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - aws-sdk-cpp.tar
