version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - yum groupinstall "Development Tools" -y
      - yum install cmake -y
      - mkdir build
      - cmake -S . -B .\build -DCMAKE_GENERATOR_PLATFORM=x64 -DVCPKG_TARGET_TRIPLET=x64-windows -DCELERO_ENABLE_TESTS
      - cmake --build build --target ALL_BUILD --config Release --verbose
      - tar -c ./build > celero.tar
      - ls -alt ./build
      - ls -alt ./build/bin
      - ./build/bin/Test*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - celero.tar
